# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2c486aacccf0c30f0e982db1db07a4c3164e2b01d15d5a919829fa89bdd9b0c33b4dab55b0746e377f90dd76beae794674d101dd43a8dc8646aa7edf4bf8fe

test:
  secret_key_base: 56dfb084ebfc06c84b51f9bfe0caf2375b1570de8782f030230bbd7be529f2d61792ce290d5558a345803ff14d1e1893f8586a07f0d2112ed4186237b3284902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
